name: 'Workflow Run Diff'
description: 'Outputs the diff between a workflow run and a previous run.'
inputs:
  GITHUB_TOKEN:
    description: 'Token to access the GitHub API'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
